version: '3'
services:
  server:
    container_name: server-p
    build: 
      context: ./server-dir
    volumes:
      - ./server-dir:/root
    restart: always
    networks:
      golang-network:
        ipv4_address: 10.131.64.69

  client:
    container_name: client-p
    build: 
      context: ./client-dir
    volumes:
      - ./client-dir:/root
    restart: always
    networks:
      golang-network:
        ipv4_address: 10.131.64.21

networks:
  golang-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.131.64.0/24
          gateway: 10.131.64.1